#! /bin/sh
# /etc/init.d/clearclassdir

### BEGIN INIT INFO
# Provides:          clearclassdir
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Clears /home/pi/class dir
# Description:       Clears /home/pi/class dir
### END INIT INFO

# If you want a command to always run, put it here

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Clearing class dir"
    find /home/pi/class -type f ! -name '*.wav' -delete
    ;;
  stop)
    echo "Stopping clearclassdir"
    ;;
  *)
    echo "Usage: /etc/init.d/clearclassdir {start|stop}"
    exit 1
    ;;
esac

exit 0